### ISSUE TITLE
Registering a Plugin

### ISSUE THREAD

**Issue by pjbrow** [percolatestudio/meteor-momentum#19]
I'm trying to create a momentum plugin in an app built with the latest version of Meteor and the Momentum package.  I've put the plugin code into a js file in the client folder of the app (plugin is called "slide").  It's an exact copy of the example plugin "slide-height".

I am getting these two errors:

`Uncaught ReferenceError: Momentum is not defined`
`Can't find momentum plugin 'slide'`

Despite `api.export(['Momentum'], 'client');` in the `package.js` of momentum, I also can't get the Momentum object in the console.

Hope I'm missing nothing too basic!

**Comment by zol** [comment]
It sounds like momentum is not being referenced as a dependancy. In the `package.js` of your plugin, write `api.use('percolate:momentum', 'client');`
