### ISSUE TITLE
Properties on a Template instance aren't defined in the Momentum context

### ISSUE THREAD

**Issue by johanbrook** [percolatestudio/meteor-momentum#20]
I really like Momentum: it really scratched my itch, great job.

However, I've noticed a weird behavior when I'm using instances of `ReactiveVar` on my template. To avoid global `Session` vars to control view state in my templates, I usually do something like this:

```coffeescript
Template.foo.created = ->
   @showDialog = new ReactiveVar(false)

Template.foo.helpers(
  showDialog: ->
    // Here, the 'showDialog' variable will be `undefined` when wrapping with Momentum.
    Template.instance().showDialog.get()
)
```

```html
<template name="foo">
{{#momentum plugin='zoom'}}
  {{#if showDialog }}
    <p>Hi!</p>
  {{/if}}
{{/momentum}}
</template>
```

When wrapping the `showDialog` helper with the `momentum` helper, the template instance variable `showDialog` will be `undefined` when calling `Template.instance()`.

When removing the `momentum` wrapper, the variable is defined.

**Comment by zol** [comment]
Hey @johanbrook, I believe you've encountered https://github.com/meteor/meteor/issues/2923 . Perhaps lobbying MDG may get a faster resolution on it (we're constantly working around it).

**Comment by johanbrook** [comment]
Oh, I see. Thanks for the link!
