### ISSUE TITLE
styling a momentum container

### ISSUE THREAD

**Issue by LarsBuur** [percolatestudio/meteor-momentum#24]
Back in november i created a pull request that has not made into your project so far. Is it a bad idea to have css selector hooks on the momentum container?

Best regards,
Lars Buur

**Comment by zol** [comment]
Hey @LarsBuur thanks for contributing! We haven't merged your PR for three reasons:

1. We never intended to 'expose' the wrapping momentum div. Its required purely for technical reasons that may go away (attaching to `._uihooks`). 
2. When reading your templates, a viewer won't see momentum's wrapping div and thus they will require special knowledge of momentum to understand that there is a div with functional significance being inserted.
3. We want to keep the interface to momentum as simple as possible. You should be able to achieve what you need to by creating an extra wrapping div. If that's not the case, let us know!

**Comment by LarsBuur** [comment]
Great - thank you very much for your answer. 

My thoughts are: Since its there then why not have an easy way to apply a selector. 
I will remove the pull request.

**Comment by zol** [comment]
Pleasure. Thanks for caring and sorry about taking so long to respond to your PR.
