### ISSUE TITLE
Add Atmosphere link as URL for this GitHub repo

### ISSUE THREAD

**Issue by dandv** [percolatestudio/meteor-momentum#29]
https://atmospherejs.com/percolate/momentum

[![Adding GitHub repo URL](https://cloud.githubusercontent.com/assets/33569/6536430/76a7d88e-c402-11e4-8883-6ab2c7b8c30a.png)](https://github.com/dandv/meteor-webix)

**Comment by tmeasday** [comment]
Hey @dandv - I'm not sure what you mean?

**Comment by Geen-Henk** [comment]
@tmeasday I think he means to add a link to the Atmosphere package in the GitHub README/description

**Comment by dandv** [comment]
[Everyone does it](https://github.com/search?utf8=%E2%9C%93&q=Add+Atmosphere+link+GitHub&type=Issues&ref=searchresults) :)

**Comment by Geen-Henk** [comment]
@dandv - all those issues are yours.. You kinda *force* everyone to do it. 

When I search for packages, I search on [Atmosphere's website](https://atmospherejs.com), not on GitHub. Why would you want a different README for GitHub holding the link to Atmosphere?

**Comment by dandv** [comment]
@Geen-Henk: I merely suggest, and most authors find it to be a good idea. I certainly haven't invented the technique.

Not sure what "different README" you're mentioning. The idea is to set the "Website" field in the repo's header to point to Atmosphere. I've added a screenshot to the OP.

Why? Because there's extra information there, such as the number of starts the package has, the number of installs, trends, related packages etc.

BTW, are you a maintainer of this repo?

**Comment by Geen-Henk** [comment]
@dandv - Why make an issue over something so trivial?

**Comment by dandv** [comment]
@Geen-Henk: exactly. I've just made a simple suggestion that has never so far received so much opposition.

**Comment by tmeasday** [comment]
Right. The "edit" button was randomly not working yesterday so I couldn't remember if you can set a separate URL or not. Makes sense.
