### ISSUE TITLE
Is it possible to only target new/injected items

### ISSUE THREAD

**Issue by andregoldstein** [percolatestudio/meteor-momentum#35]
Hi there, thanks for the hard work on this.

I'm just wondering if it's possible to only target added/injected items? Currently on page load, all items in my list would fade / growl etc, when ideally I'd like to only animate the updates/changes?

This may be more of a general question, if I can figure out how to add a different class to added items on Meteor.insert, so they are different from persistent items, then I could use the 'CSS' option. Thanks again.

**Comment by zol** [comment]
Hey,

Unfortunately, DDP doesn't differentiate between documents that are added
on load and documents that are added later on. You have to roll your own
solution to keep track of this somehow and animate accordingly.

-- Zol

*Zoltan Olah*
Partner/Engineer
http://percolatestudio.com
+1 415 696 4455

**Comment by andregoldstein** [comment]
Hey Zol, many thanks for the reply, will have a think. Thanks!
